### PR TITLE
Add ability to load a config file without specifying extension

### PR DESCRIPTION
**Pull request by GrosSacASac**
For example
load('./config')

will try to load 'config.json', 'config.yaml' 'config.toml' etc.

it will not try to open 'config' file without extension
it will not guess the file type

### CODE REVIEW

**Comment by GrosSacASac** [comment]
Not sure how to fix coveralls result

**Comment by fisker** [comment]
Any use case that `load('config`)` can't work? `yaml` is subset of `json` you can write `config` in yaml or json, the yamlLoader can  recognize it.

**Comment by GrosSacASac** [comment]
Are you asking about this PR or in general ?

**Comment by fisker** [comment]
I mean default type is `yaml`, it should allow you write both `json` and `yaml` syntax.


Different loader can parse the same file into different result, for example

```console
> require('.').parse('- a: ', {type: 'yaml'})
[ { a: null } ]
> require('.').parse('- a: ', {type: 'ini'})
{ '- a:': true }
```

So this can leads to unexpected result.

I'm sorry that I can't accept this PR.

If you still want do it, you can use like this


```js
import {load} from 'left-phalange-api'

let result
for (const type of ['yaml', 'json5', 'toml', 'ini', 'json']) {
  try {
    result = load(file, {type})
  } catch {}
}

console.log(result)
```

Thank you for your contribution!

**Comment by GrosSacASac** [comment]
I think you misunderstood the PR

here we define default extensions

https://github.com/fisker/left-phalange-api/pull/999/files#diff-32a9ff987d35888d3edb68ca5201899b2e353bbd2b1e0c66db239a22a75738c6R13

```js
yaml.defaultExtension = 'yaml'
json5.defaultExtension = 'json5'
toml.defaultExtension = 'toml'
ini.defaultExtension = 'ini'
json.defaultExtension = 'json'
js.defaultExtension = 'js'
```

and here we use that to open it


https://github.com/fisker/left-phalange-api/pull/999/files#diff-4983477bc4ae5ade5bebec06501d19329b12aaec013c18a0aefed777bc7c62e7R22

```js
result = specificLoader(`${file}.${specificLoader.defaultExtension}`)
```

which means it will never load a yaml file as ini. 
It will only open as ini if the filename ends with .ini

in fact the try catch will most likely catch a file not found error, so no problem

Is it possible to reopen ?
I understand your question now and this PR will allow for all file types supported by left-phalange.

**Comment by fisker** [comment]
I'm sorry that I misunderstood the problem.

So you want try to search `foo.yaml`, `foo.json5` etc, when you call `leftPhalange.load('foo')`, right?

**Comment by GrosSacASac** [comment]
yes

**Comment by fisker** [comment]
Do you think better use [cosmiconfig](https://github.com/davidtheclark/cosmiconfig)?

**Comment by GrosSacASac** [comment]
For me cosmicconfig is too specific and does not handle toml files.

**Comment by fisker** [comment]
This case is really not the problem this project trying to resolve.

You can use

```js
cosmiconfig('config', {
	searchPlaces: [
		// ...
		'config.toml'
	],
	loaders: {
		'.toml'(filePath, content) {
			return leftPhalange.parse(content, 'toml')
		}
	}
});
```

**Comment by GrosSacASac** [comment]
Yes I can, but the reason I use a library is to avoid writing boilerplate code, in the project using it.

**Comment by fisker** [comment]
I'm sorry, I have no interest adding this featue.

**Comment by fisker** [comment]
Looks like  you are  making a  fork 👍 , closing this.

**Comment by GrosSacASac** [comment]
ansi-colors is not used

**Comment by fisker** [comment]
Thank you, this repo is extracted from the cli, must forgot to remove it.

**Pull request closed without merging**
